# Generated by Django 5.1.1 on 2024-09-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancetask_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='maintenance_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='provider_email',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
