# Generated by Django 5.1.1 on 2024-09-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancetask_maintenance_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='provider_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
